### ISSUE TITLE
ruby: Failed to insert tramp for mysql_send_query

### ISSUE THREAD

**Issue by deepthawtz** [tmm1/hotspots#3]
Rails 2.310 (REE 1.8.7) app crashes with this message on the first request.

I'm not sure how to get more helpful information out of this, sorry.

**Comment by tmm1** [comment]
This is a known issue on OSX. I'll try to fix it soon. It should work without problems on Linux.

**Comment by deepthawtz** [comment]
ok cool. thanks for letting me know

On Mon, May 30, 2011 at 11:58 AM, tmm1 <
reply@reply.github.com>wrote:

> This is a known issue on OSX. I'll try to fix it soon. It should work
> without problems on Linux.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tmm1/hotspots/issues/3#comment_1262965

## 

Dylan Clendenin
831.331.1484

**Comment by dbalatero** [comment]
I get this message on Rails 3.0.7, REE 1.87 as well!

**Comment by jmbejar** [comment]
I'm also having this problem on Rails 3.0.12 and MRI 1.8.7.
As a workaround, I just commented out the mysql stuff
https://github.com/jmbejar/memprof/tree/disable_mysql_trace
